base:
  url: http://localhost:8090/

email:
  username: ${EMAIL}
  password: ${PASSWORD}

server:
  port: 8090

spring:
  application:
    name: security
  datasource:
    url: jdbc:mysql://${MYSQL_URL}:${MYSQL_PORT}/${DATABASE_NAME}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

security:
  jwt:
    key: ${JWT_KEY}
    user: CopBalance-Backend