server:
  port: 8092

spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://${MYSQL_URL}:${MYSQL_PORT}/${DATABASE_NAME}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka